# Generated by Django 3.2.9 on 2021-11-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fizzbuzz",
            fields=[
                ("fizzbuzz_id", models.AutoField(primary_key=True, serialize=False)),
                ("useragent", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
            ],
            options={
                "ordering": ["fizzbuzz_id"],
            },
        ),
    ]
